context:
  region: "ap-southeast-2"
  vpc: "cloud5-terraform-vpc"
  cidrs:
    "primary": "10.1.0.0/16"
    "pod": "10.2.0.0/16"

remote_states:
  "domain-zone":
    orgaization: "test"
    workspace: "default"

prefix_list:
  ipv4: []

vpc:
  name: "${vpc}"
  cidr: "${cidrs.primary}"
  secondary_cidrs:
  - "${cidrs.pod}"
  vpn_gateway_asn: 65000
  private_zones:
  - "dev/dkr.ecr.ap-northeast-2.amazonaws.com"
  - "dev/sts.ap-northeast-2.amazonaws.com"