apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::940168446867:role/multi05-eks-cluster-terraform-autoscaler-role